# Generated by Django 4.0.4 on 2022-05-22 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0002_alter_approve_id'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='UploadMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='membercreation')),
                ('activated', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bulk Creation',
                'verbose_name_plural': 'Bulk Creations',
            },
        ),
        migrations.CreateModel(
            name='Tested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtext', models.TextField()),
                ('acknownlege_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowlege', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approval.approve')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequisitionVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(default='NBL/130/1/439', editable=False, max_length=20)),
                ('payee', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=250)),
                ('qty', models.CharField(max_length=250)),
                ('rate', models.CharField(max_length=250)),
                ('details', models.CharField(max_length=250)),
                ('amount', models.CharField(max_length=250)),
                ('qty_2', models.CharField(blank=True, max_length=250, null=True)),
                ('rate_2', models.CharField(blank=True, max_length=250, null=True)),
                ('details_2', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_2', models.CharField(blank=True, max_length=250, null=True)),
                ('qty_3', models.CharField(blank=True, max_length=250, null=True)),
                ('rate_3', models.CharField(blank=True, max_length=250, null=True)),
                ('details_3', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_3', models.CharField(blank=True, max_length=250, null=True)),
                ('qty_4', models.CharField(blank=True, max_length=250, null=True)),
                ('rate_4', models.CharField(blank=True, max_length=250, null=True)),
                ('details_4', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_4', models.CharField(blank=True, max_length=250, null=True)),
                ('qty_5', models.CharField(blank=True, max_length=250, null=True)),
                ('rate_5', models.CharField(blank=True, max_length=250, null=True)),
                ('details_5', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_5', models.CharField(blank=True, max_length=250, null=True)),
                ('total', models.CharField(max_length=250)),
                ('amount_in_words', models.CharField(max_length=250)),
                ('requested_by', models.CharField(max_length=250)),
                ('acknowledge_by', models.IntegerField(default=0)),
                ('approved_by', models.IntegerField(default=0)),
                ('voucher_created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher_updated_at', models.DateField(auto_now=True)),
                ('acknowlege_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approve_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
            ],
            options={
                'verbose_name': 'Payment Requisition Voucher',
                'verbose_name_plural': 'Payment Requisition Vouchers',
                'ordering': ('-voucher_updated_at',),
            },
        ),
    ]
