# Generated by Django 4.0.4 on 2022-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_alter_paymentrequisitionvoucher_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequisitionvoucher',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentrequisitionvoucher',
            name='tracking_id',
            field=models.CharField(default='NBL/130/6/730', editable=False, max_length=20),
        ),
    ]
