# Generated by Django 4.0.4 on 2022-05-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_paymentrequisitionvoucher_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentverification',
            name='payvoucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.paymentrequisitionvoucher'),
        ),
        migrations.AlterField(
            model_name='paymentrequisitionvoucher',
            name='tracking_id',
            field=models.CharField(default='NBL/130/6/673', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentverification',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
