# Generated by Django 4.0.4 on 2022-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'is_centraladmin'), (2, 'is_acknowleger'), (3, 'is_manager'), (4, 'is_client')], null=True),
        ),
    ]
