# Generated by Django 4.0.4 on 2022-05-22 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0002_alter_approve_id'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknlowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknlowledged_by', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acknlowledge',
                'verbose_name_plural': 'Acknlowledges',
            },
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('acknowlege_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acknowledgement.acknlowledge')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='approval.approve')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client')),
            ],
            options={
                'verbose_name': 'Demo',
                'verbose_name_plural': 'Demos',
            },
        ),
    ]
